#!/bin/bash
#SBATCH -J g09_test
#SBATCH -N 1 
#SBATCH -n 128
#SBATCH -p normal
#SBATCH -o g09_test.o%j
#SBATCH -t 48:00:00
#SBATCH -A A-ch6
#SBATCH --mail-user=nmarioni@utexas.edu
#SBATCH --mail-type=end     # email me when the job finishes

set -x

filename=$1

g09 ${filename}
